version: '3.9'
services:
  nexus:
    build: .
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8080:8080"
      - "11434:11434" # Ollama API
    environment:
      - OLLAMA_HOST=http://localhost:11434
      - NEMESIS_MODE=docker

